function DispInitInfo()

% Display initialization info.
scrnReso = get(0, 'screensize');
winSize = [scrnReso(3:4)/2-[200 100] 400 200];  %center
hInfoFig = figure('Position', winSize);
movegui(hInfoFig, 'center');
hInfoFig = hInfoFig.Number;
set(hInfoFig, 'color', [.3 .3 .3]);
WindowAPI(hInfoFig, 'monitor');
WindowAPI(hInfoFig, 'Position', winSize);
WindowAPI(hInfoFig, 'Alpha', 0.8);
WindowAPI(hInfoFig, 'Clip');
WindowAPI(hInfoFig, 'TopMost');
scTxt = text(0.5, 0.5, 'Spike CLuster', ...
    'Units',    'normalized', ...
    'FontSize', 24, ...
    'FontName', 'Verdana', ...
    'HorizontalAlignment', 'center', ...
    'Color', [0 0 1], ...
    'Margin',   12);
text(0.5, 0.25, 'by Minggui Chen @Jan. 2012', ...
    'Units',    'normalized', ...
    'FontSize', 12, ...
    'FontName', 'Verdana', ...
    'HorizontalAlignment', 'center', ...
    'Color', [.9 .9 .9], ...
    'Margin',   12);
axis off;
pause(1);
close(hInfoFig);